### PR TITLE
Website repointed

### PR DESCRIPTION
**Pull request by aubertlone**
- final cleanup
- when Cypress & other tests pass, & we check Vercel deployement....
- ready to push into main (after passing checks)

### CODE REVIEW

**Review by TensionCoding — COMMENTED** [review]
Why did you rename to Svelvet Cake?

**Comment by aubertlone** [comment]
we didn't rename to svelvetcake. That was simply the name of an intermediary NPM Package we were using while in development. We are about to go live.

everything is running off of svelvet

**Comment by TensionCoding** [comment]
Well I can't wait to see it! I won't be able to make it to launch this evening but this looks so cool!

**Review by ianhnizdo — APPROVED** [review]
Final changes to the NPM package have been updated for the website and future npm installs.

**Review by sher85 — APPROVED** [review]

**Review by sher85 — APPROVED** [review]

**Review by sher85 — APPROVED** [review]

**Review by sher85 — APPROVED** [review]

**Review by sher85 — APPROVED** [review]

**Review by sher85 — APPROVED** [review]

**Review by sher85 — APPROVED** [review]

**Review by sher85 — APPROVED** [review]

**Review by sher85 — APPROVED** [review]

**Review by sher85 — APPROVED** [review]

**Review by sher85 — APPROVED** [review]

**Review by sher85 — APPROVED** [review]

**Review by sher85 — APPROVED** [review]

**Pull request merged**
